// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARnrBr2MPJ-ihOLJPkz-pdpMqEM2lXs7I',
    appId: '1:417146606456:web:97afd9946c3a964698ae8d',
    messagingSenderId: '417146606456',
    projectId: 'tutorprojecttt',
    authDomain: 'tutorprojecttt.firebaseapp.com',
    storageBucket: 'tutorprojecttt.firebasestorage.app',
    measurementId: 'G-5TL6G06TE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDCat8lIMbjhFDzaJXXlubgbM0Cq0YEM',
    appId: '1:417146606456:android:dd560d200308c27598ae8d',
    messagingSenderId: '417146606456',
    projectId: 'tutorprojecttt',
    storageBucket: 'tutorprojecttt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5nb72l6yj3N5jVoRVBJJ7p8yypUUgbw',
    appId: '1:417146606456:ios:532ead04741b977998ae8d',
    messagingSenderId: '417146606456',
    projectId: 'tutorprojecttt',
    storageBucket: 'tutorprojecttt.firebasestorage.app',
    iosBundleId: 'com.example.tutorappDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp5nb72l6yj3N5jVoRVBJJ7p8yypUUgbw',
    appId: '1:417146606456:ios:532ead04741b977998ae8d',
    messagingSenderId: '417146606456',
    projectId: 'tutorprojecttt',
    storageBucket: 'tutorprojecttt.firebasestorage.app',
    iosBundleId: 'com.example.tutorappDeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARnrBr2MPJ-ihOLJPkz-pdpMqEM2lXs7I',
    appId: '1:417146606456:web:5ed7fe552d52a00998ae8d',
    messagingSenderId: '417146606456',
    projectId: 'tutorprojecttt',
    authDomain: 'tutorprojecttt.firebaseapp.com',
    storageBucket: 'tutorprojecttt.firebasestorage.app',
    measurementId: 'G-8BXN06J7EJ',
  );
}
